# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "petri_artifacts_core"
edition = "2021"
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
paste.workspace = true

[lints]
workspace = true
