# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "safeatomic"
edition = "2021"
rust-version.workspace = true

[dependencies]
zerocopy.workspace = true

[lints]
workspace = true
