# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "vtl_array"
edition = "2021"
rust-version.workspace = true

[dependencies]
hvdef.workspace = true
inspect.workspace = true

bitvec.workspace = true

[lints]
workspace = true
