# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "kmsg"
edition = "2021"
rust-version.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
