# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "acpi_spec"
edition = "2021"
rust-version.workspace = true

[features]
default = []

alloc = []
std = ["alloc", "dep:thiserror"]

[dependencies]
open_enum.workspace = true

bitfield-struct.workspace = true
static_assertions.workspace = true
thiserror = { optional = true, workspace = true }
zerocopy.workspace = true

[lints]
workspace = true
