# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "petri_artifacts_vmm_test"
edition = "2021"
rust-version.workspace = true

[dependencies]
petri_artifacts_common.workspace = true
petri_artifacts_core.workspace = true

[lints]
workspace = true
