# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "storvsp_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true

guid = { workspace = true, features = ["mesh"] }
mesh.workspace = true

[lints]
workspace = true
