# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "hvlite_ttrpc_vmservice"
edition = "2021"

[dependencies]
mesh.workspace = true
mesh_rpc.workspace = true

prost.workspace = true

[build-dependencies]
mesh_build.workspace = true

prost-build.workspace = true

[lints]
workspace = true
