# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "arc_cyclic_builder"
edition = "2021"
rust-version.workspace = true

[dev-dependencies]
futures-executor.workspace = true

[lints]
workspace = true
