# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "tracelimit"
edition = "2021"
rust-version.workspace = true

[dependencies]
parking_lot.workspace = true
tracing.workspace = true

[lints]
workspace = true
