# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "tempfile_helpers"
edition = "2021"
rust-version.workspace = true

[dependencies]
tempfile.workspace = true

[lints]
workspace = true
