# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "mcr_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true

mesh.workspace = true
guid = { workspace = true, features = ["mesh"] }

[lints]
workspace = true
