name: Private VSO build
on:
  workflow_run:
    workflows: [Private VSO build Trampoline]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  PrivateBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      # adapted from https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
            });

            let matchArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name.startsWith("github-ref-");
            });

            if (matchArtifacts.length > 0) {
                matchArtifacts.sort((a, b) => {
                    let numA = parseInt(a.name.split('-').pop());
                    let numB = parseInt(b.name.split('-').pop());
                    return numB - numA;
                });
                let matchArtifact = matchArtifacts[0];
                console.log(matchArtifact.name);

                let download = await github.rest.actions.downloadArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: matchArtifact.id,
                    archive_format: 'zip',
                });
                let fs = require('fs');
                fs.writeFileSync(`${{ github.workspace }}/github-ref.zip`, Buffer.from(download.data));
            } else {
                console.log("No matching artifacts found");
            }

      - uses: Azure/login@v1
        with:
          # These secrets describe the HvLite-GitHub service principal and associated Azure subscription,
          # which, along with the GITHUB_TOKEN, are used to authenticate GitHub Actions to Azure with OpenID Connect.
          # The service principal has federated identity credentials configured describing which branches and
          # scenarios can be authenticated.
          client-id: ${{ secrets.OPENVMM_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENVMM_TENANT_ID }}
          subscription-id:  ${{ secrets.OPENVMM_SUBSCRIPTION_ID }}

      - name: Pull Azure Key Vault secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: 'HvLite-PATs'
          secrets: 'HvliteMirrorPAT'
        id: AzureKeyVault

      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        shell: bash
        run: pip install --user -r .github/scripts/requirements.txt

      - name: Run VSO build
        shell: bash
        run: |
          unzip github-ref.zip
          GITHUB_REF=$(cat ./github_ref)
          python .github/scripts/trigger-vso-pipeline.py 109784 ${{ steps.AzureKeyVault.outputs.HvliteMirrorPAT }} --commit ${GITHUB_REF}

      - name: Cancel VSO build
        shell: bash
        run: |
            build=$(cat build-id)
            echo "Build: $build"
            python .github/scripts/trigger-vso-pipeline.py 109784 ${{ steps.AzureKeyVault.outputs.HvliteMirrorPAT }} --cancel "$build"
        if: ${{ cancelled() }}
